### ISSUE TITLE
docutils fails to parse intersphinx interpreted text role

### ISSUE THREAD

**Issue by evanunderscore** [anntzer/defopt#1]
docutils is unable to correctly parse the following docstring:

```
    """Example function with :py:class:`enum.Enum` arguments.

    :param Choice arg: Choice to display
    :param Choice opt: Optional choice to display
    """
```

This produces the following help message:

```
<string>:1: (ERROR/3) Unknown interpreted text role "py:class".
usage: choices.py [-h] [--opt {one,two,three}] {one,two,three}

Example function with

positional arguments:
  {one,two,three}       Choice to display

optional arguments:
  -h, --help            show this help message and exit
  --opt {one,two,three}
                        Optional choice to display
```

While the parameters were correctly parsed, the parser stopped as soon as it hit the `:py:class:`directive.

This problem likely applies to any other markup specific to a Sphinx extension.

**Comment by evanunderscore** [comment]
Currently using the following workarounds:
* Use `py:obj` as the default role since it covers all of my use cases
* Display all text including unparsed elements, which is ugly but doesn't lose any information

**Comment by anntzer** [comment]
Now fixed by locally introducing a simple passthrough role implementation for standard sphinx python-domain roles.
