### ISSUE TITLE
feature request: better support for options that take multiple arguments and have a default

### ISSUE THREAD

**Issue by neelmraman** [anntzer/defopt#101]
It seems like right now, the best way to achieve something like this (while also ensuring the default shown in the help string is correct) is  `def main(*, nums: List[int] = [1, 2, 3])`, which isn't ideal for its use of a mutable default argument. Maybe adding support for variable-length tuples (e.g., `def main(*, nums: Tuple[int, ...] = (1, 2, 3))` would solve this.

**Comment by anntzer** [comment]
I think you can use `Iterable[int]` instead?
Supporting `tuple[int, ...]` would be nice too, let's say that I could consider a PR adding that :)

**Comment by neelmraman** [comment]
Ahh yeah didn't see that there was already support for some generic types. Thanks! I can also look into adding Ellipsis support.
