### ISSUE TITLE
Consume command line arguments in 2 function calls

### ISSUE THREAD

**Issue by mcarans** [anntzer/defopt#107]
I would like to pass command line arguments and have them consumed by 2 different functions.

This is related to what I raised a while back: https://github.com/anntzer/defopt/issues/91. However, I have come up with a solution that I want to discuss here as the API doesn't quite support it so I had to use internal calls in defopt.

The code is as follows:
```python
from typing import Callable, Optional
import defopt

def main(abc, defg=None, output_failures=False):
    """Generate datasets and create them in HDX

    Args:
        abc (str): lala
        defg (Optional[str]): haha
        output_failures (bool): Whether to output failures. Defaults to False

    Returns:
        str: None
    """
    print(abc, defg, output_failures)

def create(user_agent=None, user_agent_config_yaml=None, user_agent_lookup=None):
    """
    Create HDX configuration

    Args:
        user_agent (Optional[str]): User agent string. HDXPythonLibrary/X.X.X- is prefixed. Must be supplied if remoteckan is not.
        user_agent_config_yaml (Optional[str]): Path to YAML user agent configuration. Ignored if user_agent supplied. Defaults to ~/.useragent.yml.
        user_agent_lookup (Optional[str]): Lookup key for YAML. Ignored if user_agent supplied.

    Returns:
        None

    """
    print(user_agent, user_agent_config_yaml, user_agent_lookup)

def _bind_known(fn: Callable) -> Tuple[Callable, BoundArguments, List[str]]:
    parser = defopt._create_parser(fn, cli_options="all")
    with defopt._colorama_text():
        args, argv = parser.parse_known_args()
        parsed_argv = vars(args)
    try:
        func = parsed_argv.pop("_func")
    except KeyError:
        # Workaround for http://bugs.python.org/issue9253#msg186387 (and
        # https://bugs.python.org/issue29298 which blocks using required=True).
        parser.error("too few arguments")
    sig = defopt.signature(func)
    ba = sig.bind_partial()
    ba.arguments.update(parsed_argv)
    return func, ba, argv

def _run_known(func: Callable, ba: BoundArguments) -> Any:
    sig = defopt.signature(func)
    (raises,) = [
        # typing_inspect does not allow fetching metadata; see e.g. ti#82.
        arg
        for arg in getattr(sig.return_annotation, "__metadata__", [])
        if isinstance(arg, defopt._Raises)
    ]
    # The function call should occur here to minimize effects on the traceback.
    try:
        return func(*ba.args, **ba.kwargs)
    except raises as e:
        sys.exit(e)

def facade(projectmainfn: Callable):
    func, ba, argv = _bind_known(projectmainfn)
    defopt.run(create, argv=argv, cli_options="all")
    _run_known(func, ba)

if __name__ == "__main__":
    facade(main)
```

The arguments not used by `main` (projectmainfn) are consumed by `create` which is run first. I had to make `_bind_known` which is very similar to `defopt.bind` but uses `parse_known_args` instead of `parse_args` to make the above work (otherwise it will exit with unrecognized argument before `defopt.run` has the chance to consume the unused arguments). 

Could this behaviour be supported eg. by making it a parameter to `bind` whether to raise an error if there are unconsumed command line parameters or to return them where the default would be to raise an error as now?

**Comment by mcarans** [comment]
This issue could be related to https://github.com/anntzer/defopt/issues/3 since the `create` function above could take `**kwargs`

**Comment by anntzer** [comment]
Agreed, I like the idea very much.  I'll work on this, though not before a week or two at least due to higher priority deadlines approaching.

**Comment by mcarans** [comment]
Super! I realised I needed to copy part of run as well (I think):

```python
def _run_known(func: Callable, ba: BoundArguments) -> Any:
    sig = defopt.signature(func)
    (raises,) = [
        # typing_inspect does not allow fetching metadata; see e.g. ti#82.
        arg
        for arg in getattr(sig.return_annotation, "__metadata__", [])
        if isinstance(arg, defopt._Raises)
    ]
    # The function call should occur here to minimize effects on the traceback.
    try:
        return func(*ba.args, **ba.kwargs)
    except raises as e:
        sys.exit(e)
```

**Comment by anntzer** [comment]
I put up a tentative API at the https://github.com/anntzer/defopt/tree/bind_known branch; can you give it a try and tell me what you think?  Briefly:
- Make the callable returned by bind (... via partial in the new API, see next point) be a wrapper that handles exceptions if necessary).
- Make bind return a functools.partial() object so that bind() can return a single object, which seems simpler to me; one can now just call() the returned object (this is the motivation for the first point).  One can also directly introspect `bound.func` (more likely `bound.func.__wrapped__`), `bound.args`, `bound.keywords`.
- Split bind() and bind_known() as they don't return the same "number of values" (partial vs. partial-and-remaining-args).
- Also support switching "intermixed" parsing (per argparse), as that comes quite naturally as well.

The first two points break backcompat and will warrant a new major release.

**Comment by mcarans** [comment]
My unit test passed using your new functions as follows:

```python
    func, argv = defopt.bind_known(projectmainfn, cli_options="all")
    defopt.run(_create_configuration, argv=argv, cli_options="all")
    func()
```

I just want to confirm that all I need to do to correctly run the function passed to `bind_known` is run the returned wrapper ie.  `func()` - is that right?

**Comment by anntzer** [comment]
Yes.  Do you think the wording could be clearer (while remaining reasonably concise)?

**Comment by mcarans** [comment]
I'm not sure about what exceptions the wrapper catches, but assuming that it's ones specific to defopt then:

Bind wraps the passed in function so that certain exceptions correctly result in program termination. The wrapped function is returned and can be called without arguments since these are handled inside the wrapper.

**Comment by anntzer** [comment]
OK, pushed a new version.  Still needs tests though...

**Comment by mcarans** [comment]
My unit test still passes and the documentation improvements look good.

**Comment by anntzer** [comment]
This has now been merged into master.
