### ISSUE TITLE
Command line tool to run arbitrary function

### ISSUE THREAD

**Issue by evanunderscore** [anntzer/defopt#11]
It would be cool to include a tool that can run any suitably documented function:

```
$ defopt package.module.function [args]
```

This will could work well with #9 and https://github.com/python/typeshed (although a lot of the types might be too generic to sensibly handle).

Possible example:

```
$ defopt round 1.234 --ndigits 2
1.23
```

**Comment by AbeDillon** [comment]
def main(argv=None):
        argv = sys.argv[1:] if argv is None else argv
        outer_argv = argv[:1]
        inner_argv = argv[1:]
        
        def outer(path: str=""):
            inner = import_object(path)
            run(inner, argv=inner_argv)

        run(outer, argv=outer_argv)

    def import_object(path, _recursive_call=False):
        """
        Import an object from a python dot-notation path. Similar to import_module
        from importlib, but allows the path to contain objects other than packages,
        modules, and classes.
    
        Args:
            path (str): The absolute python-style path to an object
    
        Returns: the object
    
        Examples:
            >>> import_object("string.digits")
            '0123456789'
    
            >>> import_object("string.digits.__class__.__name__.upper")()
            'STR'
        """
        if (not _recursive_call) and ("." not in path):
            return globals().get(path, import_object("builtins."+path, True))
        try:
            mod_path, name = path.rsplit('.', 1)
        except ValueError as e:
            raise ValueError("%r is not a valid object path" % path) from e
        try:
            mod = importlib.import_module(mod_path)
        except ImportError:
            mod = import_object(mod_path, True)  # allow for objects within objects
        return getattr(mod, name)

**Comment by evanunderscore** [comment]
Perhaps we could reuse whatever mechanism setuptools uses for entry points? The only difference would be that you need to use a colon to denote which part needs to be imported, e.g. `package.module:object.attribute`, which I don't mind as it's more explicit.

**Comment by anntzer** [comment]
I'm going to close this even though a patch is relatively simple (per above) because
- even though defopt uses extremely "natural" annotations, in practice the callable, its parameters, and their annotations typically still need to be carefully designed to really work as CLI; e.g. the initially suggested `round` would not work because the second parameter is not keyword-only.
- it's not clear we can easily load typeshed hints at runtime.

May reopen if real use cases show up.

**Comment by anntzer** [comment]
As it turns out I had a need for this feature (to make a script defopt-runnable without declaring a dependency on it, to simplify redistribution), so I just pushed it :)
