### ISSUE TITLE
Any way to indent within tool help text without runtime / linting error?

### ISSUE THREAD

**Issue by NatPRoach** [anntzer/defopt#111]
Hello, I had a small question about how best to add an indented section to help text for tool.

If I attempt to do:
```python
my_example_tool(
    *,
    input: Path
) -> None:
    """
    Does X.

    Input should be a YAML file in the following format:
        example:
            example2: <VALUE>
    """
    pass
```
defopt complains about the indendation and fails.

If I escape the indent with `\` at the place where defopt expects a non-whitespace character, flake8 then complains about invalid escape sequences.
`W605 invalid escape sequence '\ '`

Is there a preferred way of adding indentation to help text in this manner that is flake8 compliant?

**Comment by anntzer** [comment]
This is defined by the rst syntax, which requires a double colon and a blank line:
```python
def my_example_tool(
    *,
    input: Path
) -> None:
    """
    Does X.

    Input should be a YAML file in the following format::

        example:
            example2: <VALUE>
    """
    pass
```
(any complaints about the rst syntax should go to the docutils mailing list).
