### ISSUE TITLE
pin setuptools_scm < 6.4 to support python3.6

### ISSUE THREAD

**Issue by grepinsight** [anntzer/defopt#118]
As of May 2022, the minimal version setuptools_scm supports is python 3.7.

https://github.com/pypa/setuptools_scm/commit/d65a0377a71b2915107d4e816c0f5e1724d42f82

However, because of https://github.com/anntzer/defopt/blob/f68a70b4adc7222bc237ea231571ecc752cc35b6/setup.py#L19

Installation of defopt will install setuptools_scm >= 7.0.0, and installation fails in python 3.6

**Comment by anntzer** [comment]
It shouldn't be needed, as setuptools_scm correctly sets python_requires>=3.7 in their setup.cfg (and trying locally to install with py3.6 in a clean env works just fine for me).  Can you provide a minimal repro (with an up-to-date pip) for the failure you see?

**Comment by anntzer** [comment]
Closing for lack of info, but feel free to ping again with more info.
