### ISSUE TITLE
py.typed file?

### ISSUE THREAD

**Issue by 89465127** [anntzer/defopt#121]
When using mypy on some code that uses defopt, I get the following error:

```
error: Skipping analyzing "defopt": module is installed, but missing library stubs or py.typed marker  [import]
```

Could you include a `py.typed` file?

**Comment by anntzer** [comment]
Although I like the use of type hints in special cases such as the generation of CLI argument parsers, I am also personally doubtful of the move towards statically type-checked python, and will therefore choose not to include a py.typed file (I also do not include general type hints in my other packages).
You can consider separately distributing a type stubs package (https://peps.python.org/pep-0561/) if you desire.

**Comment by anntzer** [comment]
I can only point you to the typing guide, which I'll take at face value: https://typing.readthedocs.io/en/latest/source/typing_anti_pitch.html
> Anyway, with all that said, here’s a list of possible reasons to not use static type checking in Python:
> * You simply don't want to. Python is a tool that is meant to serve you. Python is a big tent,
multi-paradigm language that generally allows you to do things in the way that best suits your needs, as best determined by you.

> You’ve made the decision that adding static types isn’t the right choice for your library. But perhaps you’d still like to help your users who do use static type checking – and maybe you have some enthusiastic would-be contributors willing to help with this.
> One option is encourage such contributors to publish a [PEP 561](https://www.python.org/dev/peps/pep-0561) stub-only package that is maintained separately from your main project. They could also contribute these stubs to the [typeshed](https://github.com/python/typeshed) project.
...
> If more users pester you about adding static types, feel free to link them to this document.
