### ISSUE TITLE
[BUG] Pyinstaller does not resolve defopt import

### ISSUE THREAD

**Issue by FalconTube** [anntzer/defopt#125]
# Description
- `defopt` is a great package for CLI creation.
- CLIs can be distributed as compiled binaries, which can be created by `pyinstaller`.
- However, `pyinstaller` fails when importing `defopt`.

# Expected behavior
- `pyinstaller` can successfully compile a package, which uses `defopt` to generate its CLI.

# Actual behavior
- `pyinstaller` compiles the package fine, but there is an error upon running the executable.
- Error is due to import of `modify_iter` from `pockets` package.

```bash
> pyinstaller main.py
...

> ./dist/main
Traceback (most recent call last):
File "main.py", line 1, in <module>
from defopt import run
File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
File "defopt.py", line 52, in <module>
File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
File "sphinxcontrib/napoleon/__init__.py", line 13, in <module>
File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
File "sphinxcontrib/napoleon/docstring.py", line 22, in <module>
ImportError: cannot import name 'modify_iter' from 'pockets' (/tmp/_MEIS0fuFS/pockets/__init__.pyc)
[36220] Failed to execute script 'main' due to unhandled exception!
```

# Solution
- Simply adjust the import from pockets (will create a PR soon).
- The `__init__.py` file in `pockets` package actually has some comments, that state the behavior of its imports: https://github.com/RobRuana/pockets/blob/master/pockets/__init__.py

### Current import
```python
# in docstring.py

from pockets import modify_iter, UnicodeMixin
```

### Working solution
```python
# in docstring.py

from pockets.iterators import modify_iter
from pockets import UnicodeMixin
```

**Comment by FalconTube** [comment]
Need to issue this in sphinxcontrib-napoleon, not here. Sorry...

**Comment by bede** [comment]
This very issue also affected me, drove me slightly loopy…

**Comment by anntzer** [comment]
I guess you could open an issue to make their imports more robust wrt. pyinstaller.

**Comment by FalconTube** [comment]
I now found, that the `sphinxcontrib-napoleon` package is archived, because it is integrated into sphinx itself.
In `defopt.py`, one can then replace in line 48:
```diff
# in defopt.py

-  from sphinxcontrib.napoleon import Config, GoogleDocstring, NumpyDocstring
+  from sphinx.ext.napoleon import Config, GoogleDocstring, NumpyDocstring
``` 
and it seems to work fine. By that, I mean that `defopt` still works as intended (test suite) and the `pyinstaller` package works.

Should I open a PR for this, here in `defopt`?

**Comment by anntzer** [comment]
No, see reason at https://github.com/anntzer/defopt/pull/97.
