### ISSUE TITLE
Support repeated options that take a single argument (action=append)

### ISSUE THREAD

**Issue by geofft** [anntzer/defopt#126]
I'd like to have a flag option for a list variable where the flag consumes a _single_ argument, but it can be repeated multiple times, instead of consuming multiple arguments. As an example of this, consider `gcc` or `ssh`: you can write something like `gcc -lssl -lcrypto foo.c bar.c`, which is parsed as two libraries to link and two source files. Or you can pass multiple forwardings with multiple `ssh -L` arguments, but each `-L` only consumes the very next argument.

I don't think it's possible to do this currently with defopt:

```python
import defopt

def main(*source: str, library: list[str] = []):
    print("{source=}\n{library=}")

defopt.run(main)
```

```
$ ./gcc.py -lssl -lcrypto foo.c bar.c
source=('foo.c', 'bar.c')
library=['crypto']
$ ./gcc.py -l ssl -l crypto foo.c bar.c
source=()
library=['crypto', 'foo.c', 'bar.c']
```

That is, each occurrence of `-l` overwrites the previous one, and if there's a space, `-l` slurps up all the remaining arguments.

The behavior I want is basically argparse's `action='append'` _without_ `nargs='*'`:

```python
import argparse

p = argparse.ArgumentParser()
p.add_argument('-l', '--library', action='append')
p.add_argument('source', nargs='*')
a = p.parse_args()
print(f"{a.source=}\n{a.library=}")
```

```
$ ./gcc.py -lssl -lcrypto foo.c bar.c
a.source=['foo.c', 'bar.c']
a.library=['ssl', 'crypto']
$ ./gcc.py -l ssl -l crypto foo.c bar.c
a.source=['foo.c', 'bar.c']
a.library=['ssl', 'crypto']
```

But as far as I can tell defopt only uses `action='append'` for list-type arguments where it also passes `nargs='*'`. Would there be interest in supporting this behavior somehow, perhaps with a flag to `defopt.run` that says I want lists not to get `nargs='*'`? Or is there already a way to do it that I missed?

(And of course - thank you for defopt, I'm excited to have not thought about argparse syntax until just now....)

**Comment by geofft** [comment]
Oh I think this is the same as #95! Not sure how I missed that before filing. I can probably make a PR....

**Comment by anntzer** [comment]
Please give it a try then :)
I would probably be OK with dropping support for some older pythons if that makes the implementation easier.
