### ISSUE TITLE
Support for blank lines and indentation in argument help

### ISSUE THREAD

**Issue by msto** [anntzer/defopt#127]
Hi, 

Would it be possible to support blank lines and nested indentation in an argument's help?

e.g. in this example, it'd be helpful to align the **special note** with its parent bullet, and add a line of space between the summary and the list of fields.

Current formatting and output:

```py
from pathlib import Path

import defopt

def main(*, in_foo: Path, in_bar: Path) -> None:
    """
    Example help text.

    Args:
        in_foo: Ipsum dolor
        in_bar: This argument has more detailed help text.
            It has multiple lines describing the format of the input file.
            And, there is a list enumerating its fields:
            - Field 1: ipsum dolor
            - Field 2: ipsum dolor
            **Special note about field 2**
            - Field 3: ipsum dolor
    """

if __name__ == "__main__":
    defopt.run(main)
```

<pre>
$ python test.py -h
usage: test.py [-h] --in-foo IN_FOO --in-bar IN_BAR

Example help text.

options:
  -h, --help       show this help message and exit
  --in-foo IN_FOO  Ipsum dolor
  --in-bar IN_BAR  This argument has more detailed help text.
                   It has multiple lines describing the format of the input file.
                   And, there is a list enumerating its fields:
                   - Field 1: ipsum dolor
                   - Field 2: ipsum dolor
                   <b>Special note about field 2</b>
                   - Field 3: ipsum dolor

</pre>

Desired formatting and output:

```py
from pathlib import Path

import defopt

def main(*, in_foo: Path, in_bar: Path) -> None:
    """
    Example help text.

    Args:
        in_foo: Ipsum dolor
        in_bar: This argument has more detailed help text.
            It has multiple lines describing the format of the input file.

            And, there is a list enumerating its fields:
            - Field 1: ipsum dolor
            - Field 2: ipsum dolor
              **Special note about field 2**
            - Field 3: ipsum dolor
    """

if __name__ == "__main__":
    defopt.run(main)
```

<pre>
$ python test.py -h
usage: test.py [-h] --in-foo IN_FOO --in-bar IN_BAR

Example help text.

options:
  -h, --help       show this help message and exit
  --in-foo IN_FOO  Ipsum dolor
  --in-bar IN_BAR  This argument has more detailed help text.
                   It has multiple lines describing the format of the input file.
                   
                   And, there is a list enumerating its fields:
                   - Field 1: ipsum dolor
                   - Field 2: ipsum dolor
                     <b>Special note about field 2</b>
                   - Field 3: ipsum dolor
</pre>

**Comment by anntzer** [comment]
Committed the fix.  Thanks for the report!
