### ISSUE TITLE
Reimplement ArgumentDefaultsHelpFormatter

### ISSUE THREAD

**Issue by evanunderscore** [anntzer/defopt#19]
* Defaults should appear on all arguments - even those without help text
* Defaults should not appear next to variable positional arguments

**Comment by evanunderscore** [comment]
This was partially fixed by #30, although defaults and types are not displayed next to parameters without help text.

**Comment by anntzer** [comment]
The issue with arguments without help text suppressing defaults was fixed in https://github.com/anntzer/defopt/commit/a6b6117ed12ef699dd3ded824035481bdae8dc06 (which also got rid of the need to override a private method in a formatter subclass).
