### ISSUE TITLE
Consistently handle documentation of *args

### ISSUE THREAD

**Issue by evanunderscore** [anntzer/defopt#31]
Forked from a discussion on #30.

> Which lets me notice an additional issue: napoleon indicates that varargs should be documented using
> 
> ```
> Parameters
> ----------
> *args : ...
> ```
>
>i.e. including the star, unescaped (and similarly for google-style), but defopt only recognizes the parameter name without the star).

I'm not sure what the official advice is for Sphinx-style docstrings - I write it as `args` because PyCharm won't accept it any other way.

If we can find consistent advice across formats, we should stick with that. If not, we'll have to handle both.

**Comment by anntzer** [comment]
None of the "official" guides offer any advice here (https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt, http://google.github.io/styleguide/pyguide.html?showone=Comments#Comments, also skimmed through various PEPs and the CPython docs source), but napoleon's examples explicitly mention the use of the unescaped the star (https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html#example-numpy, https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html#example-google).

**Comment by evanunderscore** [comment]
These are the stubs I get for each style from PyCharm:

```
def test(*args):
    """
    
    :param args: 
    :return: 
    """

def test(*args):
    """
    
    Parameters
    ----------
    args

    Returns
    -------

    """

def test(*args):
    """
    
    Args:
        *args: 

    Returns:

    """
```

Note that it only includes the `*` in the Google-style docstring. I have no idea whether this is intentional.

It's possible that Napoleon should be accepting the `*` in the input, but not including it in the output Sphinx-style docstrings, e.g. instead of `:param \*args:` it should convert to `:param args:`. I don't know whether that would be considered a bug, or a feature request for the option.

@RobRuana, would you mind giving an opinion on this?

**Comment by RobRuana** [comment]
Napoleon should accept the `*` in the input and display it in the output. If it doesn't that's a bug. The following styles should be acceptable for napoleon:
```python
def test(*args):
    """
    This is the numpydoc style.

    Parameters
    ----------
    *args:
        Positional arguments.

    Returns
    -------
    Return value.
    """

def test(*args):
    """
    This is the google style.
    
    Args:
        *args: Positional arguments.

    Returns:
        Return value.
    """
```

**Comment by RobRuana** [comment]
Also, I recommend using [sphinx-autodoc-napoleon-typehints](https://pypi.python.org/pypi/sphinx-autodoc-napoleon-typehints) to get robust type links with napoleon.

**Comment by evanunderscore** [comment]
It does accept it in the input and display it in the output, my concern is that, as far as I can tell, the pure autodoc equivalent does not expect the * (although it handles it). If you want Napoleon to retain the * in the output, we'll just have to handle both styles.

For sphinx-autodoc-napoleon-typehints, [the project it was forked from seems to work just fine with Napoleon](https://github.com/agronholm/sphinx-autodoc-typehints/issues/15), and in my experience works better. I can't figure out what the motivation was for creating that fork - possibly the same misunderstanding as in the linked issue.

**Comment by RobRuana** [comment]
The `*` should be escaped in the output. I guess I don't fully understand the issue here.

**Comment by evanunderscore** [comment]
Without Napoleon, I expect docstrings to look like this:

```
def test(*args):
    """
    This is the default Sphinx style

    :param args: Positional arguments.
    """
```

Currently defopt handles docstrings in this format. I use Napoleon to convert Google- and Numpy-style docstrings before I process them, which then looks to defopt like this:

```
def test(*args):
    """
    This is what defopt sees for your examples

    :param \*args: Positional arguments.
    """
```

The * is correctly escaped and is formatted properly by autodoc, the problem is only that defopt is not currently prepared to handle the *.

The difference in autodoc looks something like:

```
test(*args)
    This is the default Sphinx style
    Parameters: args - Positional arguments.

test(*args)
    This is what defopt sees for your examples
    Parameters: *args - Positional arguments.
```

The only difference is whether the * appears next to the description down the bottom - it's in the signature either way.

Given that the plain Sphinx-style docstrings do not require that * to be there, I was thinking Napoleon might want to strip it out, or give an option to do so. If you don't agree, defopt will handle both types.

**Comment by RobRuana** [comment]
Haha, we went through a big discussion a long time ago about how to correctly handle the `*` in `args` and `kwargs`. Originally napoleon ignored the `*` and passed them through to autodoc unmodified, so the responsibility of escaping them was left to the programmer. Our final conclusion on how best to handle `*` resulted in the current behavior, so I don't think we're going to change that any time soon.

**Comment by evanunderscore** [comment]
No problem, we'll just handle both. Thanks for your input.

**Comment by anntzer** [comment]
Now fixed, it's easy enough to just strip the asterisk.
