### ISSUE TITLE
Handle declared exceptions

### ISSUE THREAD

**Issue by evanunderscore** [anntzer/defopt#4]
Functions may optionally specify exceptions they raise:

```
def foo():
    """A function that raises an exception.

    :raises FooError: if something goes wrong
    """
```

It may be desirable to suppress the traceback in this case and only display the exception text itself. The docstring text could also be displayed, although the language may end up being a bit forced. Something like "This error is raised [text]" to make "This error is raised if something goes wrong".

**Comment by anntzer** [comment]
Mostly closed by #68.  We still don't use the docstring message, but it's not clear whether this can really be done while keeping natural-looking messages.
