### ISSUE TITLE
Evaluate docstring types in a context where the typing module is implicitly star-imported

### ISSUE THREAD

**Issue by anntzer** [anntzer/defopt#43]
It would be nice if types given in the docstring that rely on members of the typing module can be evaluated without having to actually import them from typing (this creates seemingly unused imports, which is both noisy, and not appreciated by linters).

**Comment by evanunderscore** [comment]
Does `sphinx.ext.autodoc` allow this? If it does, I'm all for it.

**Comment by anntzer** [comment]
No idea, but if it does not, it probably should...

**Comment by anntzer** [comment]
Well, looks like it's not as if autodoc was doing anything fancy with typing types anyways -- for example, after
```
diff --git a/examples/styles.py b/examples/styles.py
index f5818f7..e24f2fe 100644
--- a/examples/styles.py
+++ b/examples/styles.py
@@ -12,6 +12,7 @@ Command line usage::
     $ python styles.py sphinx 2 --farewell goodbye!
 """
 import defopt
+from typing import List
 
 
 def sphinx(integer, farewell=None):
@@ -31,7 +32,8 @@ def sphinx(integer, farewell=None):
         goodbye!
 
 
-    :param int integer: Number to square
+    :param integer: Number to square
+    :type integer: List[int]
     :keyword str farewell: Parting message
     """
     print(integer ** 2)
```
and building the docs, `List` in `List[int]` is not highlighted in any special way.  Note that this is different when using sohinx-autodoc-typehints (see the annotation example), but I would argue that sphinx-autodoc-typehint should actually follow sphinx's default (https://github.com/agronholm/sphinx-autodoc-typehints/issues/21).

**Comment by evanunderscore** [comment]
So the problem here appears to be that autodoc/intersphinx don't do anything special to take context into account; `typing.List` will work regardless of whether `typing` is imported, and `List` will not work unless it is defined locally in the file (simply importing it is not enough). I don't know whether this is a bug, a feature that has not yet been requested, or a deliberate omission.

**Comment by anntzer** [comment]
Let's defer this to the discussion on https://www.python.org/dev/peps/pep-0585/.
