### ISSUE TITLE
Expose a bit more of public API?

### ISSUE THREAD

**Issue by anntzer** [anntzer/defopt#74]
Would you consider exposing a bit more of defopt's functionality as public API?  Specifically, I had a old (but much used) piece of code which extracted global options from environment variables, using something of the form
```
@environ_options
def get_option(
    THEFOO: "doc for thefoo" = default_foo,
    THEBAR: "doc for thebar" = default_bar,
):
    pass
```
which would create a get_option function, allowing one to do `get_option("THEFOO")` which reads the THEFOO environment variable, converts it using default_foo's type, and defaults, well to default_foo.
This design (in particular, storing the docs in the annotations and using the default's type as type hints) was basically copied from https://pypi.org/project/argh/, which is the CLI helper I was using at that time.

Obviously, this is ripe for rewriting using defopt's approach of parsing the docstring.  After doing so using defopt's private API, I think defopt really just needs to expose a single additional API, `get_cli_signature(func, parsers)` (or however you want to call it), which would 1) call _parse_function_docstring; 2) additionally fill in types extracted from the docstring (so "_Doc" wouldn't be a suitable name for the object it returns -- it contains info from both the signature and the docstring); and 3) add an additional `parser` entry to the each _Param object.

Thoughts?

**Comment by evanunderscore** [comment]
I trust your judgement. Thanks!

**Comment by anntzer** [comment]
master now exposes `defopt.signature(func)` which returns a modified signature whose parameter objects include the corresponding docstring.
