### ISSUE TITLE
Help text shows positional arguments after list flags

### ISSUE THREAD

**Issue by justin39** [anntzer/defopt#84]
If I declare a positional argument and a list keyword argument:

```Python
def run(a: str, *, b: List[str]):
    """
    :param a: a positional field
    :param b: a keyword list field
    """"
    print('a:', a)
    print('b:', b)
```

Then the help text produced by defopt looks like:
`usage: testlist.py [-h] -b [B [B ...]] a`

But trying to pass arguments that way, ex. `testlist.py -b bar baz foo`, doesn't work - the positional argument needs to go first, or it looks like it's part of the list `b`. Shouldn't the help text look more like:
`usage: testlist.py a [-h] -b [B [B ...]]`
so that it's more clear the positional argument goes first?

**Comment by anntzer** [comment]
The help text is directly generated by argparse, which suffers from the same issue:
```python
from argparse import *
parser = ArgumentParser()
parser.add_argument("x")
parser.add_argument("-y", nargs="*")
parser.parse_args()
```
gives
```
usage: test.py [-h] [-y [Y [Y ...]]] x
```
so I'd suggest you open an issue on bugs.python.org instead.  Certainly I don't plan to reimplement all the help text generation separately in defopt.

**Comment by justin39** [comment]
Sounds like a fairly common argparse stumbling block - bummer. I'll close this for now, thanks!
