### ISSUE TITLE
Nested Subcommands

### ISSUE THREAD

**Issue by Spectre5** [anntzer/defopt#89]
`defopt` is easily my favorite of the many argument parsers for Python and I know it has a goal to stay fairly small.  That said, nested subcommands is one feature that I'd really like to have.  Subcommands are already supported, but sometimes a second layer can be useful.  Perhaps recursion can be used in the default parser.

I could see the definition of it being something like:

```python
defopt.run([sub1, {'sub2': [subsub1, subsub2]}])
```

Where these could then be called like

```shell
program sub1 --help
program sub2 --help  # not sure where this help would come from though
program sub2 subsub1 --help
program sub2 subsub2 --help
```

Currently I just use one subcommand depth and use dashes, like this:

```python
defopt.run([sub1, sub2_subsub1, sub2_subsub2])
```

Which can be used like:

```shell
program sub1 --help
program sub2-subsub1 --help
program sub2-subsub2 --help
```

**Comment by Spectre5** [comment]
@anntzer any chance you can do a point release with this feature?  I'd like to use in a few CLI's but would prefer it to be on PyPI.

**Comment by anntzer** [comment]
Release v6.2.0 to pypi.

**Comment by bede** [comment]
Thanks for adding this @anntzer !
